In [1]:
import sys
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([1.,2.,3.,4.,5.])
print(a+b)

[ 2.  4.  6.  8. 10.]


In [4]:
a[0]

1

In [5]:
a[0]*a[2]

3

In [6]:
a[3:5]

array([4, 5])

In [7]:
a[0::2]

array([1, 3, 5])

In [8]:
a[1:3]

array([2, 3])

# Array Data Type

In [9]:
a.dtype

dtype('int32')

In [10]:
b

array([1., 2., 3., 4., 5.])

In [11]:
b.dtype

dtype('float64')

In [12]:
np.array([9,3,0,4,9,4,8,6,5,6],dtype=float)

array([9., 3., 0., 4., 9., 4., 8., 6., 5., 6.])

In [13]:
np.array([1.,2.,3.,4.,5.,6.,7.],dtype=int)

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
np.array(['a','b','c','d','e','f'])

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [15]:
print(a/b)

[1. 1. 1. 1. 1.]


In [16]:
print(a-b)

[0. 0. 0. 0. 0.]


In [17]:
print(a*a+b*b)

[ 2.  8. 18. 32. 50.]


In [18]:
print(a**a)

[   1    4   27  256 3125]


# Dimension and Shapes

In [19]:
A=np.array([
    [1,2,3,4,5],[6,7,8,9,10]
])

In [20]:
A


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
A.shape

(2, 5)

In [22]:
A.ndim

2

In [23]:
A.size

10

In [24]:
B=np.array([
    [
        [1,2,3,4,5],[6,7,8,9,10]
    ]
    ,
    [
        [1,3,4,5,6],[7,6,5,3,2]
    ]
])

In [25]:
B

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  3,  4,  5,  6],
        [ 7,  6,  5,  3,  2]]])

In [26]:
B.size

20

In [27]:
B.shape

(2, 2, 5)

In [28]:
B.ndim

3

# Indexing and Slicing the Matrices

In [29]:
# Square Matrix
R=np.array([
    [1,2,3],[4,5,6],[7,8,9]
])

In [30]:
R

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
R.shape

(3, 3)

In [32]:
R[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
R[1]

array([4, 5, 6])

In [34]:
R[2]

array([7, 8, 9])

In [36]:
#geting the value:
#      array[Row][Coumns]
R[1][1]

5

In [41]:
R[2][2]

9

In [43]:
#Replacing the value of any row and columns:
R[1]=np.array([10,10,10])

In [54]:
R

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

# Summery Statistics

In [55]:
a=np.array([1,2,3,4,5])

In [56]:
a.sum()

15

In [57]:
a.mean()

3.0

In [59]:
a.max()

5

In [60]:
a.min()

1

In [61]:
a.std()

1.4142135623730951

In [62]:
a.var()

2.0

In [63]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [64]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
A.sum()

45

In [66]:
A.max()

9

In [67]:
A.min()

1

In [68]:
A.std()

2.581988897471611

In [69]:
A.mean()

5.0

In [70]:
A.sum(axis=0)

array([12, 15, 18])

In [71]:
A.sum(axis=1)

array([ 6, 15, 24])

In [73]:
A.sum(axis=-1)

array([ 6, 15, 24])

# Brodcasting and Vectorized Operation

In [78]:
B=np.arange(4)

In [79]:
B

array([0, 1, 2, 3])

In [80]:
B+10

array([10, 11, 12, 13])

In [84]:
[i for i in B]

[0, 1, 2, 3]

# Boolean Array

In [86]:
Array=np.array([7,8,9,10,11])

In [87]:
Array

array([ 7,  8,  9, 10, 11])

In [90]:
Array[[True,False,True,False,True]]

array([ 7,  9, 11])